// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA55diD0ZoEkiOmOyrDbEf8HF_WPJUFlL0',
    appId: '1:206713054310:web:c71e84cadf88038ddbf9a7',
    messagingSenderId: '206713054310',
    projectId: 'widespace-c7cf0',
    authDomain: 'widespace-c7cf0.firebaseapp.com',
    storageBucket: 'widespace-c7cf0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABic0DxD4E8PHz5jmstBgohxIfSAZWymw',
    appId: '1:206713054310:android:a0bfd366e0fed19cdbf9a7',
    messagingSenderId: '206713054310',
    projectId: 'widespace-c7cf0',
    storageBucket: 'widespace-c7cf0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6YSv7DXV2gW8IeAMITP5-HsACw1EQy9M',
    appId: '1:206713054310:ios:c0f5b84a759a30b0dbf9a7',
    messagingSenderId: '206713054310',
    projectId: 'widespace-c7cf0',
    storageBucket: 'widespace-c7cf0.appspot.com',
    iosClientId: '206713054310-cmi21i5edh3rjqqvhap2sbl16rahe8j2.apps.googleusercontent.com',
    iosBundleId: 'com.example.widespaceProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6YSv7DXV2gW8IeAMITP5-HsACw1EQy9M',
    appId: '1:206713054310:ios:c0f5b84a759a30b0dbf9a7',
    messagingSenderId: '206713054310',
    projectId: 'widespace-c7cf0',
    storageBucket: 'widespace-c7cf0.appspot.com',
    iosClientId: '206713054310-cmi21i5edh3rjqqvhap2sbl16rahe8j2.apps.googleusercontent.com',
    iosBundleId: 'com.example.widespaceProject',
  );
}
